---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(plotly)
library(ggridges)
library(tibbletime)
```

```{r}
triathlon_data <- read_csv("../data/all_results.csv")
```

```{r}
triathlon_data <- triathlon_data %>% 
    select(-value)

triathlon_data <- triathlon_data %>% 
    mutate(athlete_yob = as.numeric(athlete_yob))
```
```{r}
triathlon_data <- triathlon_data %>% 
    mutate(prog_year = as.numeric(format(prog_date, "%Y")),
           athlete_age = prog_year - athlete_yob)
```

base graph showing mean times per year for total/individual discipline
```{r}
q <- triathlon_data %>% 
    filter(cat_name == "Sprint") %>% 
    group_by(prog_year) %>% 
    summarize(mean_time = mean(total_time, na.rm = TRUE)) %>% 
    ggplot(aes(x = prog_year, y = mean_time)) +
    geom_line() +
    geom_point() +
    scale_x_continuous(breaks = c(2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019 )) +
    scale_y_time()

ggplotly(q)
```
```{r}
p <- triathlon_data %>% 
    filter(cat_name == "Standard") %>% 
    pivot_longer(swim_time:run_time, names_to = "splits", values_to = "split_times") %>%
    mutate(splits = fct_relevel(splits, "run_time", "t2_time", "bike_time", "t1_time", "swim_time")) %>%
    mutate(split_perc = as.numeric(split_times/as.numeric(total_time))) %>% 
    group_by(prog_year, splits) %>% 
    summarize(mean_splits_perc = mean(split_perc, na.rm = TRUE)) %>%
    ggplot(aes(y = mean_splits_perc, x = prog_year, fill = fct_inorder(splits))) +
    geom_bar(position = "fill", stat = "identity") +
    coord_flip() +
    scale_x_continuous(breaks = c(2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019 )) 

ggplotly(p)
```

```{r}
p <- triathlon_data %>% 
    filter(cat_name == "Standard") %>% 
    pivot_longer(swim_time:run_time, names_to = "splits", values_to = "split_times") %>%
    mutate(splits = fct_relevel(splits, "run_time", "t2_time", "bike_time", "t1_time", "swim_time"))%>%
    group_by(prog_year, splits)%>% 
    summarize(mean_splits = mean(split_times, na.rm = TRUE)) %>%
    ggplot(aes(y = mean_splits, x = prog_year, fill = fct_inorder(splits))) +
    geom_col() +
    coord_flip() +
    scale_x_continuous(breaks = c(2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019 )) +
    scale_y_time(labels = function(x) strftime(x, "%H:%M"))

ggplotly(p)
```

```{r}
t <- triathlon_data %>% 
    filter(cat_name == "Standard") %>%
    mutate(prog_year = as.character(prog_year)) %>% 
    ggplot(aes(y = total_time, x = prog_year, group=prog_year, fill = prog_year)) +
    geom_boxplot() +
    geom_jitter(color = "black", size = 0.4, alpha = 0.6) +
    scale_x_discrete(breaks = c(2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019 )) +
    scale_y_time(labels = function(x) strftime(x, "%H:%M")) +
    theme(legend.position = "none")

ggplotly(t)

```

```{r}
triathlon_data %>% 
    group_by(prog_year, prog_id) %>% 
    count(cat_name) %>% 
    group_by(prog_year) %>% 
    count(cat_name)
```

```{r}
triathlon_data <- triathlon_data %>% 
    mutate(cat_name = replace(cat_name, event_title == "2013 ITU World Triathlon Kitzbuehel", "Sprint")) 

triathlon_data <- triathlon_data %>% 
    mutate(cat_name = replace(cat_name, event_title == "2015 ITU World Triathlon Abu Dhabi", "Sprint"))
```

```{r}
triathlon_data %>% 
    filter(cat_name == "Standard") %>% 
    ggplot(aes(x = total_time, y = event_region_name)) +
    geom_density_ridges()
```

```{r}
sprint <- triathlon_data %>%  
    filter(cat_name == "Standard")%>%
    arrange(total_time) %>% 
    as_tbl_time(index = total_time) %>% 
    filter_time("00:30:00" ~ "01:10:00")  
   
mislabled_events <- unique(sprint$event_title)
mislabled_events <- as.list(mislabled_events)

triathlon_data %>% 
    filter(event_title == mislabled_events)

for (i in mislabled_events) {
    triathlon_data <- triathlon_data %>%  
        mutate(cat_name = replace(cat_name, event_title == i, "Standard"))
}
```

```{r}
write_csv(triathlon_data, "../data/cleaned_data.csv")
```

