---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(shiny)
library(httr)
library(rjson)
```


```{r}
result <- fromJSON(file = "../data/data.json")
api_key <- result[["api_key"]]

```

```{r}
url = 'https://api.triathlon.org/'

params = list(
  'event_id' = '90162',
  'prog_id' = '270564'
)


response <- GET(modify_url(url, path = paste("v1/","events/", 
                                             params["event_id"], 
                                             "/programs/", 
                                             params["prog_id"], 
                                             "/results",
                                             sep = "")), 
                add_headers(.headers = 
                                c(Accept= "application/json",
                                   apikey = "9f443da70aebfa2353fb5367eb675a6f")
                )
)

#murals <- content(response, as = 'parsed') 
```

```{r}
response$status_code
```
```{r}
event <- content(response, as = "parsed")
parsed_event <- do.call(rbind, event)
indiv <- parsed_event[3, 7]
indiv <- do.call(rbind, indiv)

```

```{r}
indiv2 <- do.call(rbind, indiv[1,1])
indiv2 
```


```{r}
length(indiv[[1]])
(length(event$data$results) +1)
event$data$results[[54]]
indiv <- do.call(rbind, event$data[[7]])
indiv <- as_tibble(indiv)
class(indiv)
test <- indiv %>% 
    subset(select = -c(athlete_profile_image, 
                       athlete_listing, 
                       athlete_flag, 
                       athlete_api_listing, 
                       athlete_categories)) %>% 
    filter(position != "DNF") %>% 
    unnest(splits) %>% 
    group_by(athlete_id)%>% 
    mutate(col=seq_along(athlete_id)) %>% 
    spread(key = col, value=splits) %>% 
    rename(swim_time = "1", t1_time = "2", bike_time = "3", t2_time = "4", run_time = "5")

    
event$data$event_id
```
base code to pull event results and format data frame
```{r}
url = 'https://api.triathlon.org/'

params = list(
  'event_id' = '90162',
  'prog_id' = '270564'
)

    
response <- GET(modify_url(url, path = paste("v1/","events/", 
                                             params["event_id"], 
                                             "/programs/", 
                                             params["prog_id"], 
                                             "/results",
                                             sep = "")), 
                add_headers(.headers = 
                                c(Accept= "application/json",
                                  apikey = api_key)
                )
)

event <- content(response, as = "parsed")

indiv <- do.call(rbind, event$data[[7]])
indiv <- as_tibble(indiv)

athlete_results <- indiv %>% 
    subset(select = -c(athlete_edit_date, 
                       athlete_profile_image, 
                       athlete_listing, 
                       athlete_flag, 
                       athlete_api_listing, 
                       athlete_categories,
                       validated)) %>% 
    filter(position != "DNF") %>% 
    unnest(splits) %>% 
    group_by(athlete_id)%>% 
    mutate(col=seq_along(athlete_id)) %>% 
    spread(key = col, value=splits) %>% 
    rename(swim_time = "1", 
           t1_time = "2", 
           bike_time = "3", 
           t2_time = "4", 
           run_time = "5") %>% 
    mutate(prog_id = event$data$prog_id, 
           event_id = event$data$event_id, 
           prog_name = event$data$prog_name, 
           prog_date = event$data$prog_date, 
           prog_time = event$data$prog_time, 
           prog_notes = event$data$prog_notes)

col_names <- colnames(athlete_results)

all_results <- setNames(rep("",length(col_names)), col_names)
all_results <- as_tibble(all_results)[0, ]
```


```{r}
url_2 = "https://api.triathlon.org/v1/statistics/results?analysis=count_unique&target_property=event.name&group_by=event.name|event.id|program.id|program.name"



response_event_list <- GET(url_2,
                add_headers(.headers = 
                                c(Accept= "application/json",
                                   apikey = api_key)
                )
)
response_event_list
response_event_list$status_code

event_list <- content(response_event_list, as = "parsed")

```

```{r}
indiv_events <- do.call(rbind, event_list$data[[1]])
indiv_events <- as_tibble(indiv_events)
```

```{r}
key_value <- indiv_events %>% 
    pivot_longer(c(program.id, event.id), names_to = "key", values_to = "value")

event_id <- indiv_events$event.id
event_id <- as.character(event_id)
program_id <- indiv_events$program.id
program_id <- as.character(program_id)
names(event_id) <- program_id

class(event_id)

for(key in names(event_id)){
    value <- event_id[key]
    print(paste(key, '=', value))
}
```

function for parsing data from api
```{r}
data_parse <- function(result) {
    event <- content(result, as = "parsed")
    
    indiv <- do.call(rbind, event$data[[7]])
    indiv <- as_tibble(indiv)
    
    athlete_results <- indiv %>% 
        subset(select = -c(athlete_edit_date, 
                           athlete_profile_image, 
                           athlete_listing, 
                           athlete_flag, 
                           athlete_api_listing, 
                           athlete_categories,
                           validated,
                           athlete_slug,
                           start_num)) %>% 
        filter(position != "DNF") %>% 
        unnest(splits) %>% 
        group_by(athlete_id)%>% 
        mutate(col=seq_along(athlete_id)) %>% 
        spread(key = col, value=splits) %>% 
        rename(swim_time = "1", 
               t1_time = "2", 
               bike_time = "3", 
               t2_time = "4", 
               run_time = "5") %>% 
        mutate(prog_id = event$data$prog_id, 
               event_id = event$data$event_id, 
               prog_name = event$data$prog_name, 
               prog_date = event$data$prog_date, 
               prog_time = event$data$prog_time, 
               prog_notes = event$data$prog_notes,
               event_title = event$data$event$event_title,
               event_venue = event$data$event$event_venue,
               event_country = event$data$event$event_country,
               event_latitude = event$data$event$event_latitude,
               event_longitude = event$data$event$event_longitude,
               event_date = event$data$event$event_date,
               event_country_isoa2 = event$data$event$event_country_isoa2,
               event_country_noc = event$data$event$event_country_noc,
               event_region_id = event$data$event$event_region_id,
               event_country_id = event$data$event$event_country_id,
               event_region_name = event$data$event$event_region_name,
               cat_name = event$data$event$event_specifications[[2]][1],
               temp_water = event$data$meta$temperature_water,
               temp_air = event$data$meta$temperature_air,
               wetsuit = event$data$meta$wetsuit)
}

event$data$meta$wetsuit
    
```

code to combine individual program result data into one data frame
```{r}
url = 'https://api.triathlon.org/'


col_names <- colnames(athlete_results)
all_results <- setNames(rep("",length(col_names)), col_names)
all_results <- as_tibble(all_results)[0, ]

for(key in names(event_id)){
    value <- event_id[key]
    
    response <- GET(modify_url(url, path = paste("v1/","events/", 
                                                 value, 
                                                 "/programs/", 
                                                 key, 
                                                 "/results",
                                                 sep = "")), 
                    add_headers(.headers = 
                                    c(Accept= "application/json",
                                      apikey = api_key)
                    )
    )
    single_event <- data_parse(response)
    
    all_results <- bind_rows(all_results, single_event)
}
```
```{r}
all_results <- all_results %>% 
    mutate(athlete_id = as.numeric(athlete_id),
           athlete_country_id = as.numeric(athlete_country_id),
           result_id = as.numeric(result_id),
           position = as.numeric(position),
           athlete_title = as.character(athlete_title),
           athlete_first = as.character(athlete_first),
           athlete_last = as.character(athlete_last),
           athlete_gender = as.character(athlete_gender),
           athlete_yob = as.character(athlete_yob),
           athlete_noc = as.character(athlete_noc),
           athlete_country_name = as.character(athlete_country_name),
           athlete_country_isoa2 = as.character(athlete_country_isoa2),
           total_time = as.character(total_time),
           swim_time = as.character(swim_time),
           t1_time = as.character(t1_time),
           bike_time = as.character(bike_time),
           t2_time = as.character(t2_time),
           run_time = as.character(run_time),
           cat_name = as.character(cat_name)) %>% 
    filter(!is.na(position))
```

```{r}
write_csv(all_results, "../data/all_results.csv")
```


